export const areas = {
  Ahmedabad: [
    "Ambawadi",
    "Amraiwadi",
    "Asarwa",
    "Ashram Road",
    "Aslali",
    "Astodia",
    "Bapunagar",
    "Bardolpura",
    "Behrampura",
    "Bhadra",
    "Bodakdev",
    "Bopal",
    "CG Road",
    "Chandkheda",
    "Chandlodia",
    "Changodar",
    "CTM",
    "CTM Char Rasta",
    "Dani Limbada",
    "Dariapur",
    "Delhi Chakla",
    "Delhi Darwaja",
    "Drive In Road",
    "Dudheshwar",
    "Dudheshwar Road",
    "Ellis Bridge",
    "Gandhi Road",
    "Geeta Mandir",
    "Geeta Mandir Road",
    "Ghatlodia",
    "Gheekanta",
    "Gheekanta Road",
    "Ghodasar",
    "Gomtipur",
    "Gota",
    "Gulbai Tekra",
    "Gurukul",
    "Hatkeshwar",
    "Income Tax",
    "Isanpur",
    "Jamalpur",
    "Jasodanagar",
    "Jivraj Park",
    "Jodhpur",
    "Juhapura",
    "Juna Wadaj",
    "Kalupur",
    "Kankaria",
    "Kankaria Road",
    "Kathwada",
    "Khadia",
    "Khamasa",
    "Khanpur",
    "Khokhara",
    "Krishnanagar",
    "Kuber Nagar",
    "Madhupura",
    "Manek Chowk",
    "Maninagar",
    "Meghani Nagar",
    "Memnagar",
    "Mirzapur",
    "Mirzapur Road",
    "Naranpura",
    "Naroda",
    "Naroda GIDC",
    "Naroda road",
    "Narol",
    "Nava Wadaj",
    "Navarangpura Gam",
    "Nikol",
    "Nirnay Nagar",
    "Odhav",
    "Odhav GIDC",
    "Odhav Road",
    "Paldi",
    "Pankore Naka",
    "Patharkuva",
    "Patthar Kuva",
    "Raipur",
    "Rakhial",
    "Ranip",
    "Ranna Park",
    "Ratan Pole",
    "Revdi Bazaar",
    "Sabarmati",
    "Sahijpur Bogha",
    "Sarangpur",
    "Saraspur",
    "Sardar Nagar",
    "Sarkej",
    "Sarkhej Gandhinagar Highway",
    "Satellite",
    "Satellite Road",
    "Shah Alam Road",
    "Shahibagh",
    "Shahibaug Road",
    "Shahpur",
    "Sola",
    "Sola Road",
    "Subhash Bridge",
    "Tavdipura",
    "Teen Darwaja",
    "Thakkarbapa Nagar",
    "Thaltej",
    "Usmanpura",
    "Vasna",
    "Vastral",
    "Vastrapur",
    "Vatva",
    "Vatva GIDC",
    "Vejalpur",
  ],
  Vadodara: [
    "Alkapuri",
    "Vadodara Railway Station",
    "Fatehgunj",
    "Sayajigunj",
    "Vasna",
    "Makarpura",
    "Gotri",
    "Jambusar Road",
    "Ajwa Road",
    "Tarsali",
    "Raopura",
    "Dandiya Bazar",
    "Vadodara Airport",
  ],
  Rajkot: [
    "Kalavad Road",
    "150 Feet Ring Road",
    "Mavdi",
    "Raiya Road",
    "Madhapar",
    "University Road",
    "Nana Mava",
    "Mota Mava",
    "Kothariya",
    "Ghanteshwer",
    "Bhakti Nagar",
    "Railnagar",
    "Race Course",
    "Gandhigram",
    "Gondal Road",
    "Upleta",
    "Jagnath Plot",
    "Raiya",
    "Junction Plot",
    "Munjka",
    "Vavdi",
    "Dharam Nagar",
    "Yagnik Road",
    "Yogi Nagar",
    "Jasdan",
    "Radhika Park",
    "Ambika Park",
    "Gundavadi",
    "Mavdi Chowkdi",
    "Manhar Plot",
  ],
};
